# Generated by Django 4.0.5 on 2022-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerCode', models.CharField(max_length=20)),
                ('CustomerName', models.CharField(max_length=100)),
                ('SiteCode', models.CharField(max_length=10)),
                ('InvoiceNo', models.CharField(max_length=20)),
                ('ItemNo', models.CharField(max_length=10)),
                ('SalesOrderNo', models.CharField(max_length=20)),
                ('CustomerPONo', models.CharField(max_length=20)),
                ('InvoiceDate', models.CharField(max_length=15)),
                ('Article', models.CharField(max_length=100)),
                ('EAN', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('UOM', models.CharField(max_length=10)),
                ('MRPPerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GrossAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BasicValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxableValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalInvAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('EmployeeCode', models.CharField(max_length=10)),
            ],
        ),
    ]
