# Generated by Django 4.0.5 on 2022-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='EmployeeCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='EmployeeName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
